
# Resume configs:

full_name: Saman Nezafat
title: Saman Nezafat
description: "Saman Nezafat CV"

pdf: true
pdf_url: https://github.com/onionj/cv/raw/gh-pages/saman_nezafat_cv.pdf

docx: true
docx_url: https://github.com/onionj/cv/raw/gh-pages/saman_nezafat_cv.docx

github: true
github_url: https://github.com/onionj

linkedin: true
linkedin_url: https://www.linkedin.com/in/samannzft

gmail: true
gmail_url: samannzft@gmail.com

phone: false
phone_number: ""

footer: false
site_footer_text: ""

# web pdf creator configs:

URL: https://onionj.github.io/

# template configs:

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

lang: "en-US"
